In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("G:\\내 드라이브\\2025\\2학기\\통계적 분석\\source\\python_stat_sample-master\\data\\ch2_scores_em.csv", index_col ="student number")
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [4]:
scores = np.array(df['english'])[:10]
print(scores)

[42 69 56 41 57 48 65 49 65 58]


In [5]:
scores_df = pd.DataFrame({'score' :scores},
                         index =pd.Index([ 'A', 'B', 'C', 'D', 'E',
                                           'F', 'G', 'H', 'I', 'J'], name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

array scores 를 정렬하여 중앙값 구하기

In [7]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [9]:
n = len(sorted_scores)
if n % 2 == 0 :
    m0 = sorted_scores[n//2-1]
    m1 = sorted_scores[n//2]
    median = (m0+m1) / 2
else :
    median = sorted_scores[(n+1)//2 -1]
median

56.5

구하는 내장 함수가 있다

In [10]:
np.median(sorted_scores)

56.5

#최빈값 구하기

In [12]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [13]:
pd.Series([1,2,3,4,5]).mode

<bound method Series.mode of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

# 편차
:각 데이터가 평균으로부터 떨어져 있는 정도

In [14]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [15]:
another_scores = [50,60,58,54,51,56,57,53,52,59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [19]:
np.mean(deviation)
np.mean(another_deviation)

0.0

In [20]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

-> scores 보다 another_scores의 편차가 더 작다.
편차를 비교 하기 위해 편차를 평균 내게 되면 부호 때문에 비교가 어려움 -> 제곱하여 평균내기.... 분산!

In [21]:
np.mean(deviation ** 2)

86.0

var 함수로 분산을 구할 수 있음

In [ ]:
np.var(scores)